{"uuid": "a19b0f80-d312-4ff7-a62a-84ba027321e8", "children": ["073f9943-7657-4af8-86af-ffb521852ab0"], "befores": [{"name": "fixtures_ver", "status": "broken", "statusDetails": {"message": "_pytest.outcomes.Exit: unable to communicate to Controller%d format: a number is required, not NoneType\n", "trace": "  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/TIP/wlan-testing/tests/conftest.py\", line 655, in fixtures_ver\n    obj = Fixtures_2x(configuration=get_configuration)\n  File \"/home/imgd/TIP/wlan-testing/tests/fixtures_2x.py\", line 56, in __init__\n    pytest.exit(\"unable to communicate to Controller\" + str(e))\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/outcomes.py\", line 115, in exit\n    raise Exit(msg, returncode)\n"}, "attachments": [{"name": "Controller Instantiation Failed: ", "source": "3b559c4e-de82-42f2-a7e6-d8b050ad631a-attachment.attach"}], "start": 1639043776642, "stop": 1639043776643}], "start": 1639043776642, "stop": 1639043777039}